### ISSUE TITLE
[BUG]: Segmentation Fault in MerkleTree::build on GPU for n >= 18 for Babybear

### ISSUE THREAD

**Issue by alluri-ritual** [ingonyama-zk/icicle#914]
## Description

A segmentation fault occurs in `MerkleTree::build` when the:
1.  The active device is CUDA.
2.  Using Babybear
3.  The number of leaves is `1 << 18` (262,144) or greater (e.g., `n=18`). For `n=17` (131,072 leaves), the build is successful with the same configuration.

The same code and tree size (`n=18`) work correctly if the device is CPU.
The segmentation fault happens during the `merkle_tree.build(...)` call.

### Reproduce

The following minimal Rust code demonstrates the issue.

**`Cargo.toml`:**
```toml
[package]
name = "try_babybear"
version = "0.1.0"
edition = "2021"

[dependencies]
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle.git", rev="42b4f9a36deee586233bc3e3d058ad567abb87a4" }
icicle-core = { git = "https://github.com/ingonyama-zk/icicle.git", rev="42b4f9a36deee586233bc3e3d058ad567abb87a4" }
icicle-babybear = { git = "https://github.com/ingonyama-zk/icicle.git", rev="42b4f9a36deee586233bc3e3d058ad567abb87a4" }
icicle-bn254 = { git = "https://github.com/ingonyama-zk/icicle.git", rev="42b4f9a36deee586233bc3e3d058ad567abb87a4" }
icicle-hash = { git = "https://github.com/ingonyama-zk/icicle.git", rev="42b4f9a36deee586233bc3e3d058ad567abb87a4" }
hex = "0.4"
clap = { version = "<=4.4.12", features = ["derive"] }
rand = "0.8"
```

**`src/main.rs`:**
The code works for bn254, but fails for babybear on GPU for n>=18 with segmentation fault
```rust
use clap::Parser;
use icicle_babybear::field::{ScalarCfg, ScalarField};
// use icicle_bn254::curve::{ScalarCfg, ScalarField};
use icicle_core::{
    hash::Hasher,
    merkle::{MerkleTree, MerkleTreeConfig, PaddingPolicy},
    traits::GenerateRandom,
};
use icicle_hash::blake2s::Blake2s;
use icicle_runtime::memory::HostSlice;
use icicle_runtime::stream::IcicleStream;
use std::time::Instant;

#[derive(Parser, Debug)]
struct Args {
    #[arg(short, long, default_value = "CPU")]
    device_type: String,
    #[arg(short, long, default_value_t = 18)] // Default to n=18 to show the issue
    n_val: usize,
}

fn try_load_and_set_backend_device(args: &Args) {
    if args.device_type != "CPU" {
        icicle_runtime::runtime::load_backend_from_env_or_default().unwrap();
    }
    println!("Setting device to {}", args.device_type);
    let device = icicle_runtime::Device::new(&args.device_type, 0);
    icicle_runtime::set_device(&device).unwrap();
}

fn merkle_tree_example(n: usize, _device_type: &str) {
    let test_vec = ScalarCfg::generate_random(1 << n);
    let leaf_size = std::mem::size_of::<ScalarField>() as u64;
    let nof_leafs = (1 << n) as u64;
    let hasher = Blake2s::new(leaf_size).unwrap();
    let compress = Blake2s::new(hasher.output_size() * 2).unwrap();

    let tree_height = nof_leafs.ilog2() as usize;
    let layer_hashes: Vec<&Hasher> = std::iter::once(&hasher)
        .chain(std::iter::repeat(&compress).take(tree_height))
        .collect();

    println!("Leaf Size: {}", leaf_size);
    println!("Number of Leafs: {}", 1 << n);
    println!("Hasher Output Size: {}", hasher.output_size());
    println!("Tree Height: {}", tree_height);

    let merkle_tree = MerkleTree::new(&layer_hashes, leaf_size, 0).unwrap();

    let mut config = MerkleTreeConfig::default();
    config.padding_policy = PaddingPolicy::ZeroPadding;

    let build_start = Instant::now();

    // This call is expected to segfault for n=18 on CUDA
    merkle_tree
        .build(HostSlice::from_slice(&test_vec), &config)
        .unwrap();

    println!("Merkle tree build took: {:?}", build_start.elapsed());
}

fn main() {
    let args = Args::parse();
    println!("{:?}", args);
    try_load_and_set_backend_device(&args);

    println!("--- Running Merkle Tree for n={} ---", args.n_val);
    merkle_tree_example(args.n_val, &args.device_type);
    println!("Test success!");
}
```

**To Reproduce the Segfault:**
1.  Pass the args `-d CUDA -n 18`. It works fine on CPU

## Environment

OS + Version:  Ubuntu 20.04.6 LTS
Cargo Version: 1.84.1 (66221abde 2024-11-19)
Rust Version: rustc 1.84.1 (e71f9a9a9 2025-01-27)
GPU type:  Quadro RTX 4000

**nvcc --version**

```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

**nvidia-smi:**
```bash
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro RTX 4000                Off |   00000000:00:08.0 Off |                  N/A |
| 30%   36C    P8              8W /  125W |       6MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1194      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

## Additional context

**Followup Question:**
- Would it be possible to pass leaves directly from `Device`? I noticed that `is_leaves_on_device` is private, and I am unable to directly use the vector on the device as leaves. Instead, I have to convert the array back to host and pass in the Merkle build.

**ICICLE Version**: 3.8.0, commit: 42b4f9a36deee586233bc3e3d058ad567abb87a4

Please help me debug this and let me know if I am missing anything.
